[package]
name = "psmx-assembler"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
regex = "=1.7.3"
lalrpop-util = { version = "0.20.0", features = [ "lexer" ] }

[build-dependencies]
lalrpop = "0.20.0"
